server:
  port: 8083

logging:
  level:
    org.springframework.security: TRACE

spring:
  application:
    name: Bookllegro

  datasource:
    url: jdbc:mysql://localhost:3306/bookllegro_db
    username: springuser
    password: MyPassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true